#!/usr/bin/expect -f

set timeout 10
set jar_path "/mnt/d/work/sftp_clien_task/sftp_client/target/sftp_client-1.0-SNAPSHOT-jar-with-dependencies.jar"

spawn java -jar $jar_path

# Ожидание запуска
expect "Введите хост:"
send "172.19.60.50\r"

expect "Введите порт:"
send "22\r"

expect "Введите логин:"
send "sftp_user\r"

expect "Введите пароль:"
send "test123\r"

expect {
    "Подключение к SFTP-серверу успешно." {}
    timeout { exit 1 }
}

# Проверка существования test.domain перед добавлением
send "1\r"
sleep 1
set exists 0
expect {
    -re "test\\.domain" {
        set exists 1
    }
    timeout{}
}

if {$exists} {
    send "5\r"
    expect "Введите домен / IP:"
    send "test.domain\r"
    expect {
        "Запись успешно удалена" {}
        timeout { exit 1 }
    }
}

# Добавление записи
send "4\r"
expect "Введите домен:"
send "test.domain\r"
expect "Введите IP:"
send "0.0.0.0\r"
expect {
    "Успешно: Запись добавлена" {}
    timeout { exit 1 }
}

# Проверка списка записей
send "1\r"
expect {
    -re "test\\.domain, IP: 0\\.0\\.0\\.0" {}
    timeout { exit 1 }
}

# Поиск IP по домену
send "2\r"
expect "Введите домен:"
send "test.domain\r"
expect {
    "IP-адрес: 0.0.0.0" {}
    timeout { exit 1 }
}

# Поиск домена по IP
send "3\r"
expect "Введите IP:"
send "0.0.0.0\r"
expect {
    "Домен: test.domain" {}
    timeout { exit 1 }
}

# Удаление записи
send "5\r"
expect "Введите домен / IP:"
send "test.domain\r"
expect {
    "Запись успешно удалена" {}
    timeout { exit 1 }
}

# Выход из приложения
send "6\r"
expect eof

puts "Тесты успешно пройдены"
exit 0
