#!/usr/bin/expect -f

spawn java -jar sftp_client/target/sftp_client-1.0-SNAPSHOT.jar

# Подключение
expect "Введите хост:" { send "172.19.60.50\r" }
expect "Введите порт:" { send "22\r" }
expect "Введите логин:" { send "sftp_user\r" }
expect "Введите пароль:" { send "test123\r" }

expect "Выберите действие: "

# Тест команды 4 (Добавление)
send "4\r"
expect "Введите домен: "
send "test.domain\r"
expect "Введите IP: "
send "10.0.0.1\r"
expect "Успешно: Запись добавлена"

# Тест команды 1 (Список)
send "1\r"
expect "Домен: test.domain, IP: 10.0.0.1"

# Тест команды 2 (Поиск IP)
send "2\r"
expect "Введите домен:"
send "test.domain\r"
expect "IP-адрес: 10.0.0.1"

# Тест команды 3 (Поиск домена)
send "3\r"
expect "Введите IP:"
send "10.0.0.1\r"
expect "Домен: test.domain"


# Тест команды 5 (Удаление)
send "5\r"
expect "Введите домен / IP:"
send "test.domain\r"
expect "Запись успешно удалена"

# Выход
send "6\r"
expect eof